version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - database
    expose:
      - 27017
    volumes:
      - './volumes/mongo:/data/db'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - database

  client:
    image: strompova/d3-client
    container_name: d3-client
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - client
      - server
    depends_on:
      - server
    ports:
      - 80:80

  server:
    image: strompova/d3-server
    container_name: d3-server
    build:
      context: server
      dockerfile: Dockerfile
      args:
        MONGO_URI_ARG: mongodb://root:example@mongo:27017/
    networks:
      - server
      - database
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - './volumes/server:/usr/app/.migrate'

networks:
  database: {}
  client: {}
  server: {}
