version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - database
    expose:
      - 27017
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - database

  client:
    image: strompova/d3-client
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - client
    depends_on:
      - server
    ports:
      - 80:80

  server:
    image: strompova/d3-server
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - server
      - database
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://root:example@mongo:27017/"
    ports:
      - 3000:3000
networks:
  database:
  client:
  server: